config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  resources :users, only: [:new, :create, :show]
  resources :pictures do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { maximum: 20 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pictures

  has_secure_password
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: %i[ show edit update destroy ]
  before_action :ensure_user, only: %i[ edit update destroy ]

  def index
    @pictures = Picture.all.order(updated_at: :desc)
  end

  def show
  end

  def new
    @picture = Picture.new
  end

  def edit
  end

  def create
    @picture = current_user.pictures.build(picture_params)
    render :new and return if params[:back]
    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: "新規投稿しました！" }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: "投稿を編集しました！" }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: "投稿を削除しました！" }
      format.json { head :no_content }
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  private

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def ensure_user
    redirect_to pictures_path unless @picture.user == current_user
  end

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to pictures_path
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to pictures_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to pictures_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_pictures_path
    elsif action_name == "edit"
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>友だちつながりアプリ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>友だちつながりアプリ</h1>
    </header>

    <div class="login_status">
      <% if logged_in? %>
        <%= link_to "プロフィール", user_path(current_user.id) %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
        <h3>ようこそ<%= current_user.name%>さん</h3>
      <% else %>
        <%= link_to "アカウント登録", new_user_path %>
        <%= link_to "ログイン", new_session_path %>
      <% end %>
    </div>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer>
      <p>~最近の出来事を画像と共に投稿しましょう~</p>
      <p>※画像の投稿は任意</p>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で投稿しますか？</h3>

<%= form_with(model: @picture, local: true, url: pictures_path) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @picture.title %></p>
  <p>内容:<%= @picture.content %></p>
  <p>画像:</p>
  <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>

  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/pictures/edit.html.erb
<h1>編集画面</h1>

<%= render 'form', picture: @picture %>

<%= link_to '詳細', @picture %> |
<%= link_to '一覧に戻る', pictures_path %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>

<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>画像</th>
      <th>投稿者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.content %></td>
        <td><%= "画像あり" if picture.image? %></td>
        <td><%= picture.user.name %></td>
        <td><%= link_to '詳細', picture %></td>
        <% if picture.user == current_user %>
          <td><%= link_to '編集', edit_picture_path(picture) %></td>
          <td><%= link_to '削除', picture, method: :delete, data: { confirm: '本当に削除してもいいですか？' } %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規投稿', new_picture_path %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

<%= link_to '一覧に戻る', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>タイトル:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @picture.content %>
</p>

<p>
  <strong>画像:</strong>
  <%= image_tag @picture.image.url if @picture.image? %>
</p>

<p>
  <strong>投稿者:</strong>
  <%= @picture.user.name %>
</p>

<% if @picture.user == current_user %>
  <%= link_to '編集', edit_picture_path(@picture) %> |
<% end %>
<%= link_to '一覧に戻る', pictures_path %>

app/views/users/new.html.erb
<h1>アカウント登録</h1>

<%= form_with(model: @user, local: true) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "アカウント登録" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<%= link_to '一覧に戻る', pictures_path %>